#pragma once

#include <assert.h>
#include <cuda_runtime.h>

#include <functional>
#include <type_traits>
#include <unordered_set>

#include "DDFaceMassMatrix3D.hpp"
#include "DDMassMatrix3D.hpp"
#include "DDStiffnessMatrix3D.hpp"
#include "EnsembleSpace3D.hpp"
#include "HostDeviceArray.hpp"
#include "LinearSolvers/gcro.hpp"
#include "Operator.hpp"
#include "Operators3D/MassMatrix3D.hpp"
#include "cuddh_config.hpp"
#include "cuddh_error.hpp"
#include "forall.hpp"
#include "linalg.hpp"

namespace cuddh
{
    /**
     * @brief Operator for Helmholtz domain decomposition substructured problem in 3D.
     * The scalar type scalar_t is either float or double and is the scalar type in which the substructured problem
     * is solved. The original finite element problem is always in double precision.
     */
    template <typename scalar_t>
    class DDSubstructedProblem3D : public Operator<scalar_t>
    {
        static_assert(std::is_same_v<scalar_t, float> || std::is_same_v<scalar_t, double>,
                      "scalar_t must be float or double");

    public:
        /// @brief initialize domain decomposition Helmholtz approximate solver.
        /// @param omega the Helmholtz frequency
        /// @param h_a HOST ARRAY. The variable coefficient a
        /// @param fem H1Space3D. Mesh must be generated by Mesh3D::uniform_rect
        /// @param efem EnsembleSpace3D. Must be a uniform partition of the mesh into rectangular subdomains.
        DDSubstructedProblem3D(double omega, const double *h_a, const H1Space3D &fem, const EnsembleSpace3D &efem);

        ~DDSubstructedProblem3D() = default;

        /// return the number of degrees of freedom for the substructured problem.
        int size() const { return 2 * n_lambda; }

        // Compute the right hand side `b` of the substructured problem from the
        // forcing `f` of the Helmholtz problem (i.e. the right hand side of the
        // finite element problem).
        void rhs(const double *f, scalar_t *b) const;

        // extract the finite element solution `u` from the solution of the
        // substructured problem `lambda` and the Helmholtz forcing `f`.
        void postprocess(const scalar_t *lambda, const double *f, double *u) const;

        /// @brief y <- A * x where A is the approximate inverse of the
        /// Helmholtz equation estimated by the domain decomposition method.
        void action(const scalar_t *x, scalar_t *y) const override;

        void action(scalar_t c, const scalar_t *x, scalar_t *y) const override
        {
            cuddh_verify(false, printf("DDSubstructedProblem3D::action(c, x, y) not implemented\n"));
        }

        void residual(const double *u, const double *f, double *res) const;

    private:
        void action(const double *fem_in, double *fem_out, const scalar_t *lambda_in, scalar_t *lambda_out) const;

    private:
        int g_ndof;
        int g_elem;
        int n_basis;
        int n_domains;
        int n_lambda;
        int mx_dof;
        int mx_fdof;
        int mx_elem_per_dom;

        double omega;
        double dt;

        const EnsembleSpace3D &efem;

        // B(o, i, p) = [lambda_index, dual_lambda_index] for face DOF i of subspace p.
        // The leading dimension is 3 because in 3D up to 3 faces can meet at a point.
        thrust::universal_vector<int2> _B;
        // T(o, i, p) = trace operator coefficient for face DOF i of subspace p.
        thrust::universal_vector<scalar_t> _T;

        DDStiffnessMatrix3D<scalar_t> S;
        thrust::universal_vector<scalar2<scalar_t>> alpha_beta; // (alpha, beta) time stepping coefficients

        thrust::universal_vector<scalar_t> _partition_of_unity;
    };

    extern template class DDSubstructedProblem3D<float>;

    /**
     * @brief Domain decomposition Helmholtz solver in 3D.
     * The scalar type scalar_t is either float or double and is the scalar type in which the substructured problem
     * is solved. The original finite element problem is always in double precision.
     */
    template <typename scalar_t>
    class DDH3D
    {
    public:
        DDH3D(double omega, const double *h_a, const H1Space3D &fem, const EnsembleSpace3D &efem, int kdim = 20,
              int edim = 10)
            : ndof{fem.size()},
              F(omega, h_a, fem, efem),
              solver(F.size(), F, nullptr, kdim, edim),
              lambda(F.size()),
              Y(F.size())
        {}

        int n_lambda() const { return F.size(); }

        SolverResults solve(double *x, const double *b, const SolverParams &opts = {}) const
        {
            thrust::fill(lambda.begin(), lambda.end(), scalar_t(0));
            thrust::fill(Y.begin(), Y.end(), scalar_t(0));

            scalar_t *d_L = thrust::raw_pointer_cast(lambda.data());
            scalar_t *d_Y = thrust::raw_pointer_cast(Y.data());

            F.rhs(b, d_Y);
            SolverResults out = solver.solve(d_L, d_Y, opts);

            dla::zeros(2 * ndof, x);
            F.postprocess(d_L, b, x);

            return out;
        }

    private:
        const int ndof;
        DDSubstructedProblem3D<scalar_t> F;
        GCRO<scalar_t> solver;
        mutable thrust::device_vector<scalar_t> lambda;
        mutable thrust::device_vector<scalar_t> Y;
    };

    extern template class DDH3D<float>;
} // namespace cuddh
