#pragma once

#include <assert.h>
#include <cuda_runtime.h>

#include <concepts>
#include <format>
#include <functional>
#include <type_traits>
#include <unordered_set>

#include "DDFaceMassMatrix3D.hpp"
#include "DDKernelConfig.hpp"
#include "DDMassMatrix3D.hpp"
#include "DDStiffnessMatrix3D.hpp"
#include "DDSymmetrize.hpp"
#include "DDWaveHoltz3D.hpp"
#include "EnsembleSpace3D.hpp"
#include "HostDeviceArray.hpp"
#include "LambdaDOFData.hpp"
#include "LinearSolvers/minres.hpp"
#include "Operator.hpp"
#include "Operators3D/MassMatrix3D.hpp"
#include "cuddh_config.hpp"
#include "cuddh_error.hpp"
#include "forall.hpp"
#include "linalg.hpp"

namespace cuddh
{
    /**
     * @brief Operator for Helmholtz domain decomposition substructured problem in 3D.
     * The scalar type scalar_t is either float or double and is the scalar type in which the substructured problem
     * is solved. The original finite element problem is always in double precision.
     */
    template <std::floating_point scalar_t>
    class DDSubstructuredOperator3D : public Operator<scalar_t>
    {
    public:
        /// @brief initialize domain decomposition Helmholtz approximate solver.
        /// @param omega the Helmholtz frequency
        /// @param h_a HOST ARRAY. The variable coefficient a
        /// @param fem H1Space3D. Mesh must be generated by Mesh3D::uniform_rect
        /// @param efem EnsembleSpace3D. Must be a uniform partition of the mesh into rectangular subdomains.
        /// @param config kernel launch configuration (TDOF). Block size is determined automatically from n_basis.
        /// @param waveholtz_iterations Fixed number of WaveHoltz iterations;
        ///                             -1 = residual-based stopping.
        DDSubstructuredOperator3D(double omega, const double *h_a, const H1Space3D &fem, const EnsembleSpace3D &efem,
                                  DDKernelConfig config = {}, int waveholtz_iterations = -1);

        ~DDSubstructuredOperator3D() = default;

        // Compute the right hand side `b` of the substructured problem from the
        // forcing `f` of the Helmholtz problem (i.e. the right hand side of the
        // finite element problem).
        void rhs(const double *f, scalar_t *b) const;

        // extract the finite element solution `u` from the solution of the
        // substructured problem `lambda` and the Helmholtz forcing `f`.
        void postprocess(const scalar_t *lambda, const double *f, double *u) const;

        /// @brief y <- A * x where A is the approximate inverse of the
        /// Helmholtz equation estimated by the domain decomposition method.
        void action(const scalar_t *x, scalar_t *y) const override;

        void action(scalar_t, const scalar_t *, scalar_t *) const override
        {
            cuddh_verify(false, printf("DDSubstructuredOperator3D::action(c, x, y) not implemented\n"));
        }

        /// @brief Returns a string describing the kernel launch configuration: threads per block and DOFs per thread.
        std::string kernel_str() const
        {
            return std::format("block_size = {} threads/block, tdof = {} DOFs/thread",
                               static_cast<int>(kernel_config.block_size), kernel_config.tdof);
        }

    private:
        void action(const double *fem_in, double *fem_out, const scalar_t *lambda_in, scalar_t *lambda_out) const;

    private:
        int g_ndof;
        int g_elem;
        int n_basis;
        int n_domains;
        int n_lambda;
        int mx_dof;
        int mx_fdof;
        int mx_elem_per_dom;

        DDKernelConfig kernel_config;

        const EnsembleSpace3D &efem;

        thrust::device_vector<LambdaDOFData<scalar_t>> _B;

        DDStiffnessMatrix3D<scalar_t> S;
        DDWaveHoltz<scalar_t> W;
        int waveholtz_iterations{-1};

        thrust::device_vector<scalar_t> _partition_of_unity;
        mutable thrust::device_vector<scalar_t> _work;
    };

    extern template class DDSubstructuredOperator3D<float>;
    extern template class DDSubstructuredOperator3D<double>;

    /**
     * @brief Domain decomposition Helmholtz solver in 3D.
     * The scalar type scalar_t is either float or double and is the scalar type in which the substructured problem
     * is solved. The original finite element problem is always in double precision.
     */
    template <std::floating_point scalar_t>
    class DDH3D : Solver<double>
    {
    public:
        DDH3D(double omega, const double *h_a, const H1Space3D &fem, const EnsembleSpace3D &efem,
              DDKernelConfig kernel_config = {}, int waveholtz_iterations = -1)
            : Solver<double>(2 * fem.size()),
              F(omega, h_a, fem, efem, kernel_config, waveholtz_iterations),
              solver(F),
              lambda(F.ndof()),
              Y(F.ndof())
        {}

        SolverResults solve(double *x, const double *b, SolverParams opts = {}) const override
        {
            thrust::fill(lambda.begin(), lambda.end(), scalar_t(0));

            scalar_t *d_L = thrust::raw_pointer_cast(lambda.data());
            scalar_t *d_Y = thrust::raw_pointer_cast(Y.data());

            F.rhs(b, d_Y);
            SolverResults out = solver.solve(d_L, d_Y, opts);

            F.postprocess(d_L, b, x);

            return out;
        }

        const DDSubstructuredOperator3D<scalar_t> &op() const { return F; }

    private:
        DDSubstructuredOperator3D<scalar_t> F;
        MINRES<scalar_t> solver;
        mutable thrust::device_vector<scalar_t> lambda;
        mutable thrust::device_vector<scalar_t> Y;
    };

    extern template class DDH3D<float>;
    extern template class DDH3D<double>;
} // namespace cuddh
