#ifndef CUDDH_DDH_HPP
#define CUDDH_DDH_HPP

#include <assert.h>
#include <cuda_runtime.h>

#include <functional>
#include <unordered_set>

#include "DDFaceMassMatrix.hpp"
#include "DDMassMatrix.hpp"
#include "DDStiffnessMatrix.hpp"
#include "EnsembleSpace.hpp"
#include "HostDeviceArray.hpp"
#include "Operator.hpp"
#include "Operators2D/MassMatrix.hpp"
#include "cuddh_config.hpp"
#include "cuddh_error.hpp"
#include "forall.hpp"
#include "gmres.hpp"
#include "linalg.hpp"

namespace cuddh
{
    struct bdr_data
    {
        int lambda_index = -1;
        float mass = 0.0f;
    };

    class DDSubstructedProblem : public SinglePrecisionOperator
    {
    public:
        /// @brief initialize domain decomposition Helmholtz approximate solver.
        /// @param omega the Helmholtz frequency
        /// @param h_a HOST ARRAY. The variable coefficient a
        /// @param fem H1Space2D. Mesh must be generated by Mesh2D::uniform_rect
        /// @param efem EnsembleSpace. Must be a uniform partition of the mesh into rectangular subdomains.
        DDSubstructedProblem(double omega, const double *h_a, const H1Space2D &fem, const EnsembleSpace &efem);

        ~DDSubstructedProblem() = default;

        /// return the number of degrees of freedom for the substructured problem.
        int size() const
        {
            return 2 * n_lambda;
        }

        // Compute the right hand side `b` of the substructured problem from the
        // forcing `f` of the Helmholtz problem (i.e. the right hand side of the
        // finite element problem).
        void rhs(const double *f, float *b) const;

        // extract the finite element solution `u` from the solution of the
        // substructured problem `lambda` and the Helmholtz forcing `f`.
        void postprocess(const float *lambda, const double *f, double *u) const;

        /// @brief y <- A * x where A is the approximate inverse of the
        /// Helmholtz equation estimated the domain decomposition method.
        void action(const float *x, float *y) const override;

        void residual(const double *u, const double *f, double *res) const;

    private:
        void action(const double *fem_in, double *fem_out, const float *lambda_in, float *lambda_out) const;

    private:
        int g_ndof;
        int g_elem;
        int n_basis;
        int n_domains;
        int n_lambda;
        int n_dupl;
        int mx_dof;
        int mx_fdof;
        int mx_elem_per_dom;

        double omega;
        double dt;

        const EnsembleSpace &efem;

        thrust::universal_vector<int2> _B;  // B(o, face_index, subspace) = global lambda and dual indices
        thrust::universal_vector<float> _T; // T = a * W.omega * (mi + mj) used in lambda update

        DDStiffnessMatrix S;
        thrust::universal_vector<float2> alpha_beta; // (alpha, beta) time stepping coefficients

        thrust::universal_vector<float> _partition_of_unity;
    };

    class DDH : public Operator
    {
    public:
        DDH(double omega, const double *h_a, const H1Space2D &fem, const EnsembleSpace &efem,
            SolverParams opts = {.m = 20, .maxit = 20, .tol = 1e-6})
            : ndof{fem.size()}, opts{opts}, F(omega, h_a, fem, efem), lambda(F.size()), Y(F.size())
        {}

        int n_lambda() const
        {
            return F.size();
        }

        void action(const double *x, double *y) const override
        {
            thrust::fill(lambda.begin(), lambda.end(), 0.0f);
            thrust::fill(Y.begin(), Y.end(), 0.0f);

            float *d_L = thrust::raw_pointer_cast(lambda.data());
            float *d_Y = thrust::raw_pointer_cast(Y.data());

            F.rhs(x, d_Y);
            gmres(F.size(), d_L, &F, d_Y, opts);

            zeros(2 * ndof, y);
            F.postprocess(d_L, x, y);
        }

        void action(double c, const double *x, double *y) const override
        {
            cuddh_verify(false, printf("DDH::action(c, x, y) not implemented\n"));
        }

    private:
        const int ndof;
        const SolverParams opts;
        DDSubstructedProblem F;
        mutable thrust::device_vector<float> lambda;
        mutable thrust::device_vector<float> Y;
    };
} // namespace cuddh

#endif
